version: 2.0.{build}
skip_tags: true
image: Visual Studio 2017
build_script:
  - ps: (Get-Content AhoCorasick\AhoCorasick.csproj).Replace("1.0.0-VERSION", $env:APPVEYOR_BUILD_VERSION) | Set-Content AhoCorasick\AhoCorasick.csproj
  - dotnet restore
  - dotnet build -c Release
  - dotnet pack --include-symbols --include-source -c Release AhoCorasick
test_script:
  - dotnet test AhoCorasick.Tests\AhoCorasick.Tests.csproj
  - nuget.exe install OpenCover -ExcludeVersion
  - OpenCover\tools\OpenCover.Console.exe -register:user -filter:"+[Ganss.Text]*" -target:"C:\Program Files\dotnet\dotnet.exe" "-targetargs:test AhoCorasick.Tests\AhoCorasick.Tests.csproj" -returntargetcode -hideskipped:All -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
artifacts:
  - path: 'AhoCorasick\**\*.nupkg'
